### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.sparkleshare.SparkleShare#1]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by hbons** [comment]
screenshot links now in the appdata file.

**Comment by LeandroStanger** [comment]
![captura de tela de 2018-07-28 18-53-42](https://user-images.githubusercontent.com/26097419/43360896-a84da4ce-9297-11e8-9004-b7f2857abe39.png)
![captura de tela de 2018-07-28 18-53-30](https://user-images.githubusercontent.com/26097419/43360897-ac8079cc-9297-11e8-8542-91e0c1a48b00.png)
